FROM golang:1.17.2-alpine AS builder

WORKDIR /src
COPY . .

RUN go mod download && \
    CGO_ENABLED=0 go build -ldflags="-s -w" -o "SignTools"

FROM alpine:3.14.2

WORKDIR /

COPY --from=builder "/src/SignTools" "/"

CMD ["/SignTools"]
EXPOSE 8080
